### PR TITLE
Add Compression xplat test zips

### PR DESCRIPTION
**Pull request by ianhays**
This commit resolves https://github.com/dotnet/corefx/issues/4992 by adding test zips that contain files with paths that are potentially invalid. The corresponding tests are being added in https://github.com/dotnet/corefx/pull/5262

@stephentoub I guess? Not sure who owns this repo.

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM

**Comment by ianhays** [comment]
@stephentoub I need to upload a new nuget package to dotnet-corefxtestdata with these additions. Do you know how that's done or know who handles updates to the testdata packages?

**Comment by stephentoub** [comment]
I don't.  @joshfree or @weshaggard?

**Comment by joshfree** [comment]
@ianhays we can chat.  @FiveTimesTheFun setup that repo.

**Comment by weshaggard** [comment]
I think it is done manually, I can probably give you access to push to that feed.

**Comment by ianhays** [comment]
>I think it is done manually, I can probably give you access to push to that feed.

>@ianhays we can chat. @FiveTimesTheFun setup that repo.

Whatever works :) https://github.com/dotnet/corefx/pull/5262/ requires assets just added to this repo.

**Pull request merged**
