### PR TITLE
Add System.Media test data

### PR DESCRIPTION
**Pull request by hughbe**
Necessary for https://github.com/dotnet/corefx/issues/31426

/cc @danmosemsft

### CODE REVIEW

**Comment by danmosemsft** [comment]
What is the origin of this data? Is it fully public domain? BTW Wikipedia media archive has been a good source of public domain media in the past, but self created is better still.

@safern can sign off on this one as I will be out for a bit.

**Comment by safern** [comment]
@hughbe any update on the question above?

**Comment by hughbe** [comment]
Hey If I recall correctly I downloaded a sample wav file from http://www.music.helsinki.fi/tmt/opetus/uusmedia/esim/index-e.html

Then I used NAudio to convert the file into the various wav file formats supported/not supported by System.Media

**Comment by danmosemsft** [comment]
@hughbe let me ask internally about license requirements. Alternatively if you were to just say "hello world" and use that I am pretty confident we would be good.. 😺

**Comment by danmosemsft** [comment]
@safern perhaps you could upload some definitely free sound (like your voice) in order to unblock this checkin and thus the related work?

**Comment by safern** [comment]
> @safern perhaps you could upload some definitely free sound (like your voice) in order to unblock this checkin and thus the related work?

Sure.

**Comment by safern** [comment]
@danmosemsft done.

**Comment by safern** [comment]
Will produce the package and push it to myget.

**Pull request merged**
