### PR TITLE
Adding contoso.com client and server certificates

### PR DESCRIPTION
**Pull request by CIPop**
Adding NDX PKI valid certificates to improve System.Net.Security testing.

@bartonjs @davidsh @josguil PTAL
/cc: @stephentoub @SidharthNabar 

The merge and build of this depot is a prerequisite for https://github.com/dotnet/corefx/pull/4389

### CODE REVIEW

**Comment by davidsh** [comment]
LGTM

**Comment by bartonjs** [comment]
This doesn't feel like it really applies to the X509 tests, particularly the .inf files. Seems like it should be another test data package (or just included in your test library as hex encoded data)

**Comment by CIPop** [comment]
> doesn't feel like it really applies to the X509 tests

You're right: created a new package: System.Net.TestData to use for System.Net.* namespaces.
Not a big fan of encoded data within the tests.

**Comment by CIPop** [comment]
>  particularly the .inf files

I've added these here just because there's no other proper place to put files used in the request process. I'd like to have them under source control as they properly describe the certificate requirements.

**Pull request merged**
