### PR TITLE
Add additional test assets for System.Drawing based on Mono's unit tests

### PR DESCRIPTION
**Pull request by qmfrederik**
In preparation of dotnet/corefx#23797, this adds assets used by Mono's test for System.Drawing to the System.Drawing.Common.TestData NuGet package.

### CODE REVIEW

**Comment by mellinoe** [comment]
Can you bump up the `<version>` tag as well, to 1.0.4?

**Comment by qmfrederik** [comment]
@mellinoe Done.

**Comment by mellinoe** [comment]
I pushed version 1.0.4 to myget.

**Pull request merged**
