### PR TITLE
Add font resources to test data

### PR DESCRIPTION
**Pull request by hughbe**
Required for https://github.com/dotnet/corefx/pull/21552

@mellinoe

### CODE REVIEW

**Comment by hughbe** [comment]
I've just tested by running `nuget pack System.Drawing.Common.TestData.nuspec` and it packs successfully

**Comment by mellinoe** [comment]
Thanks! I will build this in a bit and upload a new version.

**Comment by hughbe** [comment]
No rush - I am waiting on your big PR before addressing any feedback or rebasing :)

**Comment by mellinoe** [comment]
I published version 1.0.1, although it's not showing up in the myget UI yet. I think you should be able to move forward with your other PR now.

**Comment by hughbe** [comment]
Beaut

**Pull request merged**
