### PR TITLE
Revert "Adding image file with ole header"

### PR DESCRIPTION
**Pull request by Anipik**
Reverts dotnet/corefx-testdata#31

The source of the binary is not clear. so currently removing it from the repo
If it is required we can add some different ole image later on

### CODE REVIEW

**Comment by ViktorHofer** [comment]
This change is not sufficient. You need to increment the package version and upload it as described in the readme

**Comment by ViktorHofer** [comment]
I will deal with consuming the new package /packages as that's anyway necessary because I bumped all package versions

**Comment by Anipik** [comment]
okay cool thanks. I will upload the package

**Comment by ViktorHofer** [comment]
Don't forget to submit a new PR here

**Pull request merged**
