### PR TITLE
Adding image file with ole header

### PR DESCRIPTION
**Pull request by Anipik**
Related to https://github.com/dotnet/corefx/issues/36439
Related Corefx PR https://github.com/dotnet/corefx/pull/36891

### CODE REVIEW

**Comment by safern** [comment]
How did you produce that image?

**Comment by Anipik** [comment]
Image has been provided person who opened the issue. It is from NorthWind Database

**Comment by safern** [comment]
Ok, I just want to make sure there are no licence and compliance issues from using that image.

**Comment by Anipik** [comment]
> Ok, I just want to make sure there are no licence and compliance issues from using that image.

It seems like microsoft is the one that distributes this dataset https://technet.microsoft.com/en-us/bb399411(v=vs.91)

**Comment by ViktorHofer** [comment]
Make sure to upload the package to the dotnetfeed, not myget.

**Pull request merged**
