### PR TITLE
Remove the friendly name attribute from System.Net PFX private keys

### PR DESCRIPTION
**Pull request by davidsh**
Similar to what was done in #9 for the X509 tests, this PR will remove the friendly name attribute from the PFX files used in the System.Net tests. This will prevent hitting the Windows bug dealing with parallel PFX import.

Used the tool from: https://github.com/bartonjs/pfx-stripfriendlyname.

Contributes to https://github.com/dotnet/corefx/issues/9543 and https://github.com/dotnet/corefx/issues/23341

### CODE REVIEW

**Comment by stephentoub** [comment]
Thanks for doing this.

**Comment by davidsh** [comment]
Validated that the friendly name was removed by running "openssl pkcs12 -info -in NAME-OF-FILE.pfx" on each PFX file.

Before removing friendlyname:
```
Shrouded Keybag: pbeWithSHA1And3-KeyTripleDES-CBC, Iteration 2000
Bag Attributes
    localKeyID: 01 00 00 00
    Microsoft CSP Name: Microsoft Strong Cryptographic Provider
    friendlyName: CertReq-165d5273-51c5-4e15-bc0e-52c7eeaab95b
```

After removing friendlyname:
```
Shrouded Keybag: pbeWithSHA1And3-KeyTripleDES-CBC, Iteration 2000
Bag Attributes
    localKeyID: 01 00 00 00
    Microsoft CSP Name: Microsoft Strong Cryptographic Provider
```

**Comment by davidsh** [comment]
cc: @weshaggard @safern @bartonjs

According to the OneNote instructions for "How to store large test data for CoreFX tests"
>Run nuget pack locally on your nupkg, and ask Wes, Santi, or Joe to push to myget.

I need to get this package built and pushed to MYGET.  Can you help me with that?  I don't have permissions to do that.

Then, I'll change the CoreFx side of this in the test sources to ingest this updated package.

**Comment by davidsh** [comment]
cc: @caesar1995 @karelz

**Comment by weshaggard** [comment]
@davidsh if you can point me at the package offline I will upload it for you.

**Comment by davidsh** [comment]
@weshaggard I don't understand how to build the NuGet packages.  This repro just has .nuspec files and there is no build script.  So, how do I actually build the package and do the "nuget pack" step??

**Comment by weshaggard** [comment]
Just get nuget.exe and call "nuget pack" on the nuspec.

**Comment by davidsh** [comment]
I did that.  I sent you offline email with the link.

**Pull request merged**
